name: goreleaser

on:
  push:
    branches:
      - 'master'
      - 'beta'
    tags:
      - 'v*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      -
        name: Build Web
        run: |
          npm install yarn -g
          npm install -g @quasar/cli
          chmod +x upx.sh;cd Web;yarn install;quasar build
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Tests
        run: |
          go mod tidy
          go test -v ./...
      -
        name: Install UPX
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: |
          sudo apt-get install upx-ucl
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
